services:
  web:
    image: ghcr.io/mohamadhoseinraad/3x-ui-telegram-bot:latest
    command: ["start-web"]
    env_file:
      - .env
    environment:
      DB_FILE: /data/xui_bot_.db
    ports:
      - "5500:5500"
    volumes:
      - bot_data:/data
    restart: unless-stopped

  bot:
    image: ghcr.io/mohamadhoseinraad/3x-ui-telegram-bot:latest
    command: ["start-bot"]
    env_file:
      - .env
    environment:
      DB_FILE: /data/xui_bot_.db
    volumes:
      - bot_data:/data
    restart: unless-stopped

volumes:
  bot_data: